// <auto-generated />
using System;
using LocalizeStay.Modules.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalizeStay.Modules.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("PreselectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TradeName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LegalName")
                        .HasDatabaseName("ix_partners_legal_name");

                    b.HasIndex("PreselectionId")
                        .HasDatabaseName("ix_partners_preselection_id");

                    b.ToTable("partners", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.CurationReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurationReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("curation_reference");

                    b.Property<Guid>("PropertyOnboardingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("ReturnedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("returned_by");

                    b.HasKey("Id");

                    b.HasIndex("PropertyOnboardingId", "ReturnedAt")
                        .HasDatabaseName("ix_curation_returns_property_onboarding_id_returned_at");

                    b.ToTable("curation_returns", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("PayloadFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_fingerprint");

                    b.Property<Guid>("PropertyOnboardingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("PropertyOnboardingId", "Key", "Scope")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_keys_property_onboarding_id_key_scope");

                    b.ToTable("idempotency_keys", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DuplicateReviewRequiresDecision")
                        .HasColumnType("boolean");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_status");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreselectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PropertySimilarityKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("property_similarity_key");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("close_reason_code");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TargetSubmissionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_property_onboardings_lifecycle_status");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("ix_property_onboardings_opened_at");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_property_onboardings_partner_id");

                    b.HasIndex("PropertySimilarityKey")
                        .IsUnique()
                        .HasDatabaseName("ix_property_onboardings_active_similarity_unique")
                        .HasFilter("lifecycle_status <> 'Closed'");

                    b.HasIndex("TargetSubmissionAt")
                        .HasDatabaseName("ix_property_onboardings_target_submission_at");

                    b.ToTable("property_onboardings", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.ReadinessGate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PropertyOnboardingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("validated_by");

                    b.HasKey("Id");

                    b.HasIndex("PropertyOnboardingId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_readiness_gates_property_onboarding_id_type");

                    b.ToTable("readiness_gates", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.SharedKernel.Auditing.BusinessAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_entries_correlation_id");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredOnUtc")
                        .HasDatabaseName("ix_audit_entries_aggregate_occurred");

                    b.ToTable("audit_entries", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.ToTable("outbox_messages", "inventory");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.Partners.Partner", b =>
                {
                    b.OwnsOne("LocalizeStay.Modules.Inventory.Domain.Partners.Contact", "PrimaryContact", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("contact_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("PartnerId");

                            b1.ToTable("partners", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.OwnsOne("LocalizeStay.Modules.Inventory.Domain.Partners.LegalIdentifier", "LegalIdentifier", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("legal_identifier_country_code");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("legal_identifier_normalized_value");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("legal_identifier_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("legal_identifier_value");

                            b1.HasKey("PartnerId");

                            b1.HasIndex("CountryCode", "Type", "NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ix_partners_legal_identifier_unique");

                            b1.ToTable("partners", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.Navigation("LegalIdentifier")
                        .IsRequired();

                    b.Navigation("PrimaryContact")
                        .IsRequired();
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.CurationReturn", b =>
                {
                    b.HasOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", null)
                        .WithMany("CurationReturns")
                        .HasForeignKey("PropertyOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curation_returns_property_onboarding_id");

                    b.OwnsMany("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.CurationReturnIssue", "Issues", b1 =>
                        {
                            b1.Property<Guid>("CurationReturnId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000);

                            b1.Property<string>("OwnerType")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("RelatedGateType")
                                .HasMaxLength(50);

                            b1.HasKey("CurationReturnId", "__synthesizedOrdinal");

                            b1.ToTable("curation_returns", "inventory");

                            b1
                                .ToJson("issues")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CurationReturnId");
                        });

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.IdempotencyKey", b =>
                {
                    b.HasOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", null)
                        .WithMany()
                        .HasForeignKey("PropertyOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_keys_property_onboarding_id");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", b =>
                {
                    b.OwnsMany("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.CommunicationRecord", "CommunicationRecords", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("channel");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("created_by");

                            b1.Property<DateTimeOffset>("ProcessedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("processed_at");

                            b1.Property<bool>("ProcessedWithinSla")
                                .HasColumnType("boolean")
                                .HasColumnName("processed_within_sla");

                            b1.Property<Guid>("PropertyOnboardingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ReceivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("received_at");

                            b1.Property<string>("ResultSummary")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("result_summary");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyOnboardingId", "ProcessedWithinSla")
                                .HasDatabaseName("ix_communication_records_property_onboarding_id_processed_within_sla");

                            b1.ToTable("communication_records", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PropertyOnboardingId");
                        });

                    b.OwnsMany("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.DuplicateReview", "DuplicateReviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("decision");

                            b1.Property<Guid?>("ExistingPropertyId")
                                .HasColumnType("uuid")
                                .HasColumnName("existing_property_id");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("justification");

                            b1.Property<Guid>("PropertyOnboardingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<string>("ReviewedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("reviewed_by");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyOnboardingId");

                            b1.ToTable("duplicate_reviews", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PropertyOnboardingId");
                        });

                    b.OwnsMany("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PendingIssue", "PendingIssues", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssigneeId")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("assignee_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset>("OpenedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("opened_at");

                            b1.Property<string>("OpenedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("opened_by");

                            b1.Property<string>("OwnerType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("owner_type");

                            b1.Property<Guid>("PropertyOnboardingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("RelatedGateType")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("related_gate_type");

                            b1.Property<string>("ResolutionNote")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("resolution_note");

                            b1.Property<DateTimeOffset?>("ResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("resolved_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset?>("TargetAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("target_at");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyOnboardingId", "Status")
                                .HasDatabaseName("ix_pending_issues_property_onboarding_id_status");

                            b1.ToTable("pending_issues", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PropertyOnboardingId");
                        });

                    b.OwnsOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.Property", "Property", b1 =>
                        {
                            b1.Property<Guid>("PropertyOnboardingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DestinationId")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("property_destination_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("character varying(180)")
                                .HasColumnName("property_name");

                            b1.HasKey("PropertyOnboardingId");

                            b1.ToTable("property_onboardings", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("PropertyOnboardingId");

                            b1.OwnsOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("PropertyOnboardingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("property_address_city");

                                    b2.Property<string>("Complement")
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("property_address_complement");

                                    b2.Property<string>("CountryCode")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("property_address_country_code");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("property_address_district");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("property_address_number");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("property_address_postal_code");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("character varying(80)")
                                        .HasColumnName("property_address_state");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(180)
                                        .HasColumnType("character varying(180)")
                                        .HasColumnName("property_address_street");

                                    b2.HasKey("PropertyOnboardingId");

                                    b2.ToTable("property_onboardings", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("PropertyOnboardingId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("CommunicationRecords");

                    b.Navigation("DuplicateReviews");

                    b.Navigation("PendingIssues");

                    b.Navigation("Property")
                        .IsRequired();
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.ReadinessGate", b =>
                {
                    b.HasOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", null)
                        .WithMany("ReadinessGates")
                        .HasForeignKey("PropertyOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readiness_gates_property_onboarding_id");

                    b.OwnsOne("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.ContractReference", "ContractReference", b1 =>
                        {
                            b1.Property<Guid>("ReadinessGateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContractNumber")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("contract_number");

                            b1.Property<string>("RepositoryReference")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("contract_repository_reference");

                            b1.PrimitiveCollection<string>("ResponsibleParties")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("contract_responsible_parties");

                            b1.Property<DateTimeOffset>("SignedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("contract_signed_at");

                            b1.HasKey("ReadinessGateId");

                            b1.ToTable("readiness_gates", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("ReadinessGateId");
                        });

                    b.OwnsMany("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.EvidenceReference", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("ReadinessGateId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(300);

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.HasKey("ReadinessGateId", "__synthesizedOrdinal");

                            b1.ToTable("readiness_gates", "inventory");

                            b1
                                .ToJson("evidence")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReadinessGateId");
                        });

                    b.Navigation("ContractReference");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("LocalizeStay.Modules.Inventory.Domain.PropertyOnboardings.PropertyOnboarding", b =>
                {
                    b.Navigation("CurationReturns");

                    b.Navigation("ReadinessGates");
                });
#pragma warning restore 612, 618
        }
    }
}
